name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Triggers on git tags like v1.0.0, v2.1.3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Tag(s)
        id: tag
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "LATEST_TAG=false" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
            echo "LATEST_TAG=true" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.TAG }}
            ${{ steps.tag.outputs.LATEST_TAG && format('ghcr.io/{0}:latest', github.repository) }}

      - name: Notify on Failure
        if: failure()
        uses: appleboy/telegram-action@v1.0.1
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            ❌ Build Failed: ${{ github.repo }} @ ${{ github.ref }}
            Workflow: ${{ github.workflow }}
            Triggered by: ${{ github.actor }}
            Log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
